APP_HOST: "localhost"
APP_PORT: "8080"
ES_CLUSTER_HOSTS: "http://localhost:9200"
ES_HTTP_TIMEOUT_MS: "50000"
ES_SCENARIOS: "[{\"case\":\"1\",\"url\":\"http://localhost:8080/es_load/item\",\"rates\":[1000],\"duration\":300,\"max_workers\":1000},{\"case\":\"1\",\"url\":\"http://localhost:8080/es_load/item\",\"rates\":[2000],\"duration\":300,\"max_workers\":1000},{\"case\":\"1\",\"url\":\"http://localhost:8080/es_load/item\",\"rates\":[3000],\"duration\":300,\"max_workers\":1000}]"
