APP_HOST: "localhost"
APP_PORT: "8080"
ES_CLUSTER_HOSTS: "http://localhost:9200"
ES_HTTP_TIMEOUT_MS: "50000"
ES_SCENARIOS: "[{\"case\":1,\"url\":\"http://localhost:8080/es_load/item\",\"rates\":[100],\"duration\":30,\"max_workers\":100}]"
